"""initial schema

Revision ID: 2fb36d36ba00
Revises: 
Create Date: 2026-08-17 16:43:11.083510
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2fb36d36ba00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('normalized_name', sa.String(length=240), nullable=False),
    sa.Column('slug', sa.String(length=260), nullable=False),
    sa.Column('logo_url', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=160), nullable=True),
    sa.Column('size', sa.String(length=60), nullable=True),
    sa.Column('headquarters_city', sa.String(length=120), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('active_job_count', sa.Integer(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_normalized_name'), 'companies', ['normalized_name'], unique=True)
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('courses',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=320), nullable=False),
    sa.Column('provider', sa.String(length=240), nullable=True),
    sa.Column('format', sa.String(length=40), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('certification_offered', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    op.create_index(op.f('ix_courses_slug'), 'courses', ['slug'], unique=True)
    op.create_table('institutions',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=320), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('sector', sa.String(length=40), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=600), nullable=True),
    sa.Column('logo_url', sa.String(length=1000), nullable=True),
    sa.Column('accreditation', sa.String(length=200), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institutions'))
    )
    op.create_index(op.f('ix_institutions_city'), 'institutions', ['city'], unique=False)
    op.create_index(op.f('ix_institutions_name'), 'institutions', ['name'], unique=False)
    op.create_index(op.f('ix_institutions_slug'), 'institutions', ['slug'], unique=True)
    op.create_table('job_categories',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active_job_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_categories'))
    )
    op.create_index(op.f('ix_job_categories_slug'), 'job_categories', ['slug'], unique=True)
    op.create_table('job_sources',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('connector_key', sa.String(length=80), nullable=False),
    sa.Column('website_url', sa.String(length=600), nullable=True),
    sa.Column('attribution_label', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('fetch_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('requires_credentials', sa.Boolean(), nullable=False),
    sa.Column('credential_env_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('total_jobs_collected', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('is_seed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_sources'))
    )
    op.create_index(op.f('ix_job_sources_connector_key'), 'job_sources', ['connector_key'], unique=False)
    op.create_index(op.f('ix_job_sources_enabled'), 'job_sources', ['enabled'], unique=False)
    op.create_index(op.f('ix_job_sources_slug'), 'job_sources', ['slug'], unique=True)
    op.create_index(op.f('ix_job_sources_status'), 'job_sources', ['status'], unique=False)
    op.create_index(op.f('ix_job_sources_type'), 'job_sources', ['type'], unique=False)
    op.create_table('skills',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('google_sub', name=op.f('uq_users_google_sub'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('admin_audit_logs',
    sa.Column('admin_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], name=op.f('fk_admin_audit_logs_admin_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_audit_logs'))
    )
    op.create_index(op.f('ix_admin_audit_logs_action'), 'admin_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_admin_user_id'), 'admin_audit_logs', ['admin_user_id'], unique=False)
    op.create_index('ix_admin_audit_logs_created', 'admin_audit_logs', ['created_at'], unique=False)
    op.create_table('analytics_events',
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('anon_id', sa.String(length=64), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_analytics_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_events'))
    )
    op.create_index(op.f('ix_analytics_events_anon_id'), 'analytics_events', ['anon_id'], unique=False)
    op.create_index('ix_analytics_events_entity', 'analytics_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index('ix_analytics_events_type_created', 'analytics_events', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_table('campuses',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_campuses_institution_id_institutions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campuses'))
    )
    op.create_index(op.f('ix_campuses_city'), 'campuses', ['city'], unique=False)
    op.create_index(op.f('ix_campuses_institution_id'), 'campuses', ['institution_id'], unique=False)
    op.create_table('job_alerts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('keywords', sa.String(length=300), nullable=True),
    sa.Column('cities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provinces', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('employment_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('experience_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('remote_only', sa.Boolean(), nullable=False),
    sa.Column('government_only', sa.Boolean(), nullable=False),
    sa.Column('internship_only', sa.Boolean(), nullable=False),
    sa.Column('salary_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_job_cursor', sa.DateTime(timezone=True), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.Column('open_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_job_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_alerts'))
    )
    op.create_index('ix_job_alerts_active_frequency', 'job_alerts', ['is_active', 'frequency'], unique=False)
    op.create_index(op.f('ix_job_alerts_is_active'), 'job_alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_job_alerts_user_id'), 'job_alerts', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_job_id', sa.String(length=255), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('posted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('company_name_raw', sa.String(length=300), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('normalized_title', sa.String(length=400), nullable=False),
    sa.Column('slug', sa.String(length=460), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('normalized_description', sa.Text(), nullable=False),
    sa.Column('responsibilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('benefits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('location_raw', sa.String(length=300), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('city_slug', sa.String(length=140), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('work_mode', sa.String(length=20), nullable=False),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('employment_type', sa.String(length=30), nullable=False),
    sa.Column('experience_level', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('secondary_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_internship', sa.Boolean(), nullable=False),
    sa.Column('is_government', sa.Boolean(), nullable=False),
    sa.Column('is_fresh_graduate_friendly', sa.Boolean(), nullable=False),
    sa.Column('education_requirement', sa.String(length=80), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('classification_method', sa.String(length=30), nullable=False),
    sa.Column('salary_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=8), nullable=True),
    sa.Column('salary_period', sa.String(length=16), nullable=True),
    sa.Column('salary_is_estimated', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('apply_url_ok', sa.Boolean(), nullable=True),
    sa.Column('apply_url', sa.String(length=2000), nullable=False),
    sa.Column('apply_url_hash', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('quality_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('canonical_job_id', sa.UUID(), nullable=True),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_sponsored', sa.Boolean(), nullable=False),
    sa.Column('featured_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hidden_by_admin', sa.Boolean(), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('apply_click_count', sa.Integer(), nullable=False),
    sa.Column('save_count', sa.Integer(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(company_name_raw, '')), 'B') || setweight(to_tsvector('english', coalesce(city, '') || ' ' || coalesce(province, '')), 'B') || setweight(to_tsvector('english', coalesce(normalized_description, '')), 'C')", persisted=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_job_id'], ['jobs.id'], name=op.f('fk_jobs_canonical_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_jobs_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['posted_by_user_id'], ['users.id'], name=op.f('fk_jobs_posted_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], name=op.f('fk_jobs_source_id_job_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('source_id', 'source_job_id', name='uq_jobs_source_id_source_job_id')
    )
    op.create_index('ix_jobs_apply_url_hash', 'jobs', ['apply_url_hash'], unique=False)
    op.create_index(op.f('ix_jobs_canonical_job_id'), 'jobs', ['canonical_job_id'], unique=False)
    op.create_index(op.f('ix_jobs_category'), 'jobs', ['category'], unique=False)
    op.create_index('ix_jobs_category_status', 'jobs', ['category', 'status'], unique=False)
    op.create_index(op.f('ix_jobs_city'), 'jobs', ['city'], unique=False)
    op.create_index(op.f('ix_jobs_city_slug'), 'jobs', ['city_slug'], unique=False)
    op.create_index('ix_jobs_city_status', 'jobs', ['city', 'status'], unique=False)
    op.create_index(op.f('ix_jobs_company_id'), 'jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_jobs_country'), 'jobs', ['country'], unique=False)
    op.create_index(op.f('ix_jobs_deadline'), 'jobs', ['deadline'], unique=False)
    op.create_index(op.f('ix_jobs_education_requirement'), 'jobs', ['education_requirement'], unique=False)
    op.create_index(op.f('ix_jobs_employment_type'), 'jobs', ['employment_type'], unique=False)
    op.create_index(op.f('ix_jobs_experience_level'), 'jobs', ['experience_level'], unique=False)
    op.create_index('ix_jobs_fingerprint', 'jobs', ['content_fingerprint'], unique=False)
    op.create_index(op.f('ix_jobs_hidden_by_admin'), 'jobs', ['hidden_by_admin'], unique=False)
    op.create_index(op.f('ix_jobs_is_canonical'), 'jobs', ['is_canonical'], unique=False)
    op.create_index(op.f('ix_jobs_is_featured'), 'jobs', ['is_featured'], unique=False)
    op.create_index(op.f('ix_jobs_is_fresh_graduate_friendly'), 'jobs', ['is_fresh_graduate_friendly'], unique=False)
    op.create_index(op.f('ix_jobs_is_government'), 'jobs', ['is_government'], unique=False)
    op.create_index(op.f('ix_jobs_is_internship'), 'jobs', ['is_internship'], unique=False)
    op.create_index(op.f('ix_jobs_is_remote'), 'jobs', ['is_remote'], unique=False)
    op.create_index(op.f('ix_jobs_last_seen_at'), 'jobs', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_jobs_normalized_title'), 'jobs', ['normalized_title'], unique=False)
    op.create_index(op.f('ix_jobs_origin'), 'jobs', ['origin'], unique=False)
    op.create_index(op.f('ix_jobs_posted_at'), 'jobs', ['posted_at'], unique=False)
    op.create_index(op.f('ix_jobs_province'), 'jobs', ['province'], unique=False)
    op.create_index(op.f('ix_jobs_quality_score'), 'jobs', ['quality_score'], unique=False)
    op.create_index('ix_jobs_search_vector', 'jobs', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_jobs_slug'), 'jobs', ['slug'], unique=True)
    op.create_index(op.f('ix_jobs_source_id'), 'jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_jobs_source_job_id'), 'jobs', ['source_job_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index('ix_jobs_status_posted', 'jobs', ['status', 'posted_at'], unique=False)
    op.create_index('ix_jobs_status_quality', 'jobs', ['status', 'quality_score'], unique=False)
    op.create_index(op.f('ix_jobs_work_mode'), 'jobs', ['work_mode'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('headline', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('education_level', sa.String(length=80), nullable=True),
    sa.Column('degree', sa.String(length=160), nullable=True),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('experience_level', sa.String(length=40), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_job_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=8), nullable=False),
    sa.Column('remote_preference', sa.String(length=20), nullable=True),
    sa.Column('open_to_relocation', sa.Boolean(), nullable=False),
    sa.Column('cv_object_key', sa.String(length=500), nullable=True),
    sa.Column('profile_completion', sa.Integer(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_profiles_user_id'))
    )
    op.create_index(op.f('ix_profiles_city'), 'profiles', ['city'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_refresh_tokens_user_expires', 'refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('scholarships',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=320), nullable=False),
    sa.Column('provider', sa.String(length=240), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.String(length=60), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.String(length=160), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('apply_url', sa.String(length=2000), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_scholarships_institution_id_institutions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scholarships'))
    )
    op.create_index(op.f('ix_scholarships_deadline'), 'scholarships', ['deadline'], unique=False)
    op.create_index(op.f('ix_scholarships_slug'), 'scholarships', ['slug'], unique=True)
    op.create_index(op.f('ix_scholarships_status'), 'scholarships', ['status'], unique=False)
    op.create_table('search_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_search_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_logs'))
    )
    op.create_index(op.f('ix_search_logs_category'), 'search_logs', ['category'], unique=False)
    op.create_index(op.f('ix_search_logs_city'), 'search_logs', ['city'], unique=False)
    op.create_index('ix_search_logs_created', 'search_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_logs_query'), 'search_logs', ['query'], unique=False)
    op.create_index(op.f('ix_search_logs_user_id'), 'search_logs', ['user_id'], unique=False)
    op.create_table('source_runs',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=40), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('parsed_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=120), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], name=op.f('fk_source_runs_source_id_job_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_runs'))
    )
    op.create_index(op.f('ix_source_runs_source_id'), 'source_runs', ['source_id'], unique=False)
    op.create_index('ix_source_runs_source_started', 'source_runs', ['source_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_source_runs_status'), 'source_runs', ['status'], unique=False)
    op.create_table('verification_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_verification_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_tokens')),
    sa.UniqueConstraint('token_hash', name='uq_verification_tokens_token_hash')
    )
    op.create_index(op.f('ix_verification_tokens_user_id'), 'verification_tokens', ['user_id'], unique=False)
    op.create_table('alert_matches',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['job_alerts.id'], name=op.f('fk_alert_matches_alert_id_job_alerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_alert_matches_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_matches'))
    )
    op.create_index(op.f('ix_alert_matches_alert_id'), 'alert_matches', ['alert_id'], unique=False)
    op.create_index('ix_alert_matches_alert_job', 'alert_matches', ['alert_id', 'job_id'], unique=True)
    op.create_index(op.f('ix_alert_matches_job_id'), 'alert_matches', ['job_id'], unique=False)
    op.create_table('job_duplicates',
    sa.Column('canonical_job_id', sa.UUID(), nullable=False),
    sa.Column('duplicate_job_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('reviewed_by_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_job_id'], ['jobs.id'], name=op.f('fk_job_duplicates_canonical_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['duplicate_job_id'], ['jobs.id'], name=op.f('fk_job_duplicates_duplicate_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_duplicates')),
    sa.UniqueConstraint('canonical_job_id', 'duplicate_job_id', name='uq_job_duplicates_pair')
    )
    op.create_index(op.f('ix_job_duplicates_canonical_job_id'), 'job_duplicates', ['canonical_job_id'], unique=False)
    op.create_index('ix_job_duplicates_confidence', 'job_duplicates', ['confidence'], unique=False)
    op.create_index(op.f('ix_job_duplicates_duplicate_job_id'), 'job_duplicates', ['duplicate_job_id'], unique=False)
    op.create_table('job_events',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=60), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_events_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_events'))
    )
    op.create_index(op.f('ix_job_events_event_type'), 'job_events', ['event_type'], unique=False)
    op.create_index('ix_job_events_job_created', 'job_events', ['job_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_table('job_locations',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('city_slug', sa.String(length=140), nullable=True),
    sa.Column('province', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_locations_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_locations')),
    sa.UniqueConstraint('job_id', 'city_slug', name='uq_job_locations_job_id_city_slug')
    )
    op.create_index(op.f('ix_job_locations_city_slug'), 'job_locations', ['city_slug'], unique=False)
    op.create_index(op.f('ix_job_locations_job_id'), 'job_locations', ['job_id'], unique=False)
    op.create_table('job_skills',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_skills_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_job_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_skills')),
    sa.UniqueConstraint('job_id', 'skill_id', name='uq_job_skills_job_id_skill_id')
    )
    op.create_index(op.f('ix_job_skills_job_id'), 'job_skills', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_skills_skill_id'), 'job_skills', ['skill_id'], unique=False)
    op.create_table('job_view_daily',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('apply_clicks', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_view_daily_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_view_daily')),
    sa.UniqueConstraint('job_id', 'day', name='uq_job_view_daily_job_id_day')
    )
    op.create_index(op.f('ix_job_view_daily_day'), 'job_view_daily', ['day'], unique=False)
    op.create_index(op.f('ix_job_view_daily_job_id'), 'job_view_daily', ['job_id'], unique=False)
    op.create_table('programs',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=320), nullable=False),
    sa.Column('level', sa.String(length=60), nullable=True),
    sa.Column('field', sa.String(length=160), nullable=True),
    sa.Column('duration_years', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('fee_per_semester', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], name=op.f('fk_programs_campus_id_campuses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_programs_institution_id_institutions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programs'))
    )
    op.create_index(op.f('ix_programs_field'), 'programs', ['field'], unique=False)
    op.create_index(op.f('ix_programs_institution_id'), 'programs', ['institution_id'], unique=False)
    op.create_index(op.f('ix_programs_slug'), 'programs', ['slug'], unique=True)
    op.create_table('reports',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('reporter_email', sa.String(length=320), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_reports_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_reports_resolved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reports_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_job_id'), 'reports', ['job_id'], unique=False)
    op.create_index(op.f('ix_reports_reason'), 'reports', ['reason'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index('ix_reports_status_created', 'reports', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('saved_jobs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('folder', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_saved_jobs_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_jobs')),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_saved_jobs_user_id_job_id')
    )
    op.create_index(op.f('ix_saved_jobs_job_id'), 'saved_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_saved_jobs_user_id'), 'saved_jobs', ['user_id'], unique=False)
    op.create_table('admission_cycles',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('apply_url', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_admission_cycles_institution_id_institutions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_admission_cycles_program_id_programs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admission_cycles'))
    )
    op.create_index(op.f('ix_admission_cycles_deadline'), 'admission_cycles', ['deadline'], unique=False)
    op.create_index(op.f('ix_admission_cycles_institution_id'), 'admission_cycles', ['institution_id'], unique=False)
    op.create_index(op.f('ix_admission_cycles_program_id'), 'admission_cycles', ['program_id'], unique=False)
    op.create_index(op.f('ix_admission_cycles_status'), 'admission_cycles', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admission_cycles_status'), table_name='admission_cycles')
    op.drop_index(op.f('ix_admission_cycles_program_id'), table_name='admission_cycles')
    op.drop_index(op.f('ix_admission_cycles_institution_id'), table_name='admission_cycles')
    op.drop_index(op.f('ix_admission_cycles_deadline'), table_name='admission_cycles')
    op.drop_table('admission_cycles')
    op.drop_index(op.f('ix_saved_jobs_user_id'), table_name='saved_jobs')
    op.drop_index(op.f('ix_saved_jobs_job_id'), table_name='saved_jobs')
    op.drop_table('saved_jobs')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index('ix_reports_status_created', table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_reason'), table_name='reports')
    op.drop_index(op.f('ix_reports_job_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_programs_slug'), table_name='programs')
    op.drop_index(op.f('ix_programs_institution_id'), table_name='programs')
    op.drop_index(op.f('ix_programs_field'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_job_view_daily_job_id'), table_name='job_view_daily')
    op.drop_index(op.f('ix_job_view_daily_day'), table_name='job_view_daily')
    op.drop_table('job_view_daily')
    op.drop_index(op.f('ix_job_skills_skill_id'), table_name='job_skills')
    op.drop_index(op.f('ix_job_skills_job_id'), table_name='job_skills')
    op.drop_table('job_skills')
    op.drop_index(op.f('ix_job_locations_job_id'), table_name='job_locations')
    op.drop_index(op.f('ix_job_locations_city_slug'), table_name='job_locations')
    op.drop_table('job_locations')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_index('ix_job_events_job_created', table_name='job_events')
    op.drop_index(op.f('ix_job_events_event_type'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_job_duplicates_duplicate_job_id'), table_name='job_duplicates')
    op.drop_index('ix_job_duplicates_confidence', table_name='job_duplicates')
    op.drop_index(op.f('ix_job_duplicates_canonical_job_id'), table_name='job_duplicates')
    op.drop_table('job_duplicates')
    op.drop_index(op.f('ix_alert_matches_job_id'), table_name='alert_matches')
    op.drop_index('ix_alert_matches_alert_job', table_name='alert_matches')
    op.drop_index(op.f('ix_alert_matches_alert_id'), table_name='alert_matches')
    op.drop_table('alert_matches')
    op.drop_index(op.f('ix_verification_tokens_user_id'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    op.drop_index(op.f('ix_source_runs_status'), table_name='source_runs')
    op.drop_index('ix_source_runs_source_started', table_name='source_runs')
    op.drop_index(op.f('ix_source_runs_source_id'), table_name='source_runs')
    op.drop_table('source_runs')
    op.drop_index(op.f('ix_search_logs_user_id'), table_name='search_logs')
    op.drop_index(op.f('ix_search_logs_query'), table_name='search_logs')
    op.drop_index('ix_search_logs_created', table_name='search_logs')
    op.drop_index(op.f('ix_search_logs_city'), table_name='search_logs')
    op.drop_index(op.f('ix_search_logs_category'), table_name='search_logs')
    op.drop_table('search_logs')
    op.drop_index(op.f('ix_scholarships_status'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_slug'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_deadline'), table_name='scholarships')
    op.drop_table('scholarships')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_user_expires', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_profiles_city'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_jobs_work_mode'), table_name='jobs')
    op.drop_index('ix_jobs_status_quality', table_name='jobs')
    op.drop_index('ix_jobs_status_posted', table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_source_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_source_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_slug'), table_name='jobs')
    op.drop_index('ix_jobs_search_vector', table_name='jobs', postgresql_using='gin')
    op.drop_index(op.f('ix_jobs_quality_score'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_province'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_posted_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_origin'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_normalized_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_last_seen_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_remote'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_internship'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_government'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_fresh_graduate_friendly'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_featured'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_canonical'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_hidden_by_admin'), table_name='jobs')
    op.drop_index('ix_jobs_fingerprint', table_name='jobs')
    op.drop_index(op.f('ix_jobs_experience_level'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_employment_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_education_requirement'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_deadline'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_country'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_id'), table_name='jobs')
    op.drop_index('ix_jobs_city_status', table_name='jobs')
    op.drop_index(op.f('ix_jobs_city_slug'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_city'), table_name='jobs')
    op.drop_index('ix_jobs_category_status', table_name='jobs')
    op.drop_index(op.f('ix_jobs_category'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_canonical_job_id'), table_name='jobs')
    op.drop_index('ix_jobs_apply_url_hash', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_job_alerts_user_id'), table_name='job_alerts')
    op.drop_index(op.f('ix_job_alerts_is_active'), table_name='job_alerts')
    op.drop_index('ix_job_alerts_active_frequency', table_name='job_alerts')
    op.drop_table('job_alerts')
    op.drop_index(op.f('ix_campuses_institution_id'), table_name='campuses')
    op.drop_index(op.f('ix_campuses_city'), table_name='campuses')
    op.drop_table('campuses')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index('ix_analytics_events_type_created', table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_index('ix_analytics_events_entity', table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_anon_id'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index('ix_admin_audit_logs_created', table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_admin_user_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_action'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_slug'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_job_sources_type'), table_name='job_sources')
    op.drop_index(op.f('ix_job_sources_status'), table_name='job_sources')
    op.drop_index(op.f('ix_job_sources_slug'), table_name='job_sources')
    op.drop_index(op.f('ix_job_sources_enabled'), table_name='job_sources')
    op.drop_index(op.f('ix_job_sources_connector_key'), table_name='job_sources')
    op.drop_table('job_sources')
    op.drop_index(op.f('ix_job_categories_slug'), table_name='job_categories')
    op.drop_table('job_categories')
    op.drop_index(op.f('ix_institutions_slug'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_name'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_city'), table_name='institutions')
    op.drop_table('institutions')
    op.drop_index(op.f('ix_courses_slug'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_index(op.f('ix_companies_normalized_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
